/**
 * Render the composed one-pager plain text into HTML for storage/email.
 */

function escapeHtml(s) {
  if (typeof s !== 'string') return '';
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Convert plain-text one-pager to HTML. Treats ALL CAPS lines as headings; lines starting with "- " or "* " as list items.
 * @param {string} bodyText - Plain text report (no markdown)
 * @param {{ title?: string } } opts
 * @returns {string} Full HTML document
 */
export function textToHtml(bodyText, { title = 'Product Pulse Weekly' } = {}) {
  const lines = bodyText.split(/\n/).map((l) => l.trim()).filter(Boolean);
  const blocks = [];
  let listItems = [];

  function flushList() {
    if (listItems.length) {
      blocks.push('<ul>\n' + listItems.map((t) => `  <li>${escapeHtml(t)}</li>`).join('\n') + '\n</ul>');
      listItems = [];
    }
  }

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const isAllCaps = trimmed === trimmed.toUpperCase() && trimmed.length > 1 && /[A-Z]/.test(trimmed);
    if (isAllCaps) {
      flushList();
      blocks.push('<h2>' + escapeHtml(trimmed) + '</h2>');
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      listItems.push(trimmed.slice(2));
    } else {
      flushList();
      blocks.push('<p>' + escapeHtml(trimmed) + '</p>');
    }
  }
  flushList();

  const body = blocks.join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif; background: #f5f7fb; margin: 0; padding: 24px 8px; }
    .email-shell { max-width: 720px; margin: 0 auto; background: #ffffff; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); padding: 24px 20px 28px; line-height: 1.6; color: #141414; }
    h1 { font-size: 1.5rem; margin: 0 0 4px; color: #111827; }
    h2 { font-size: 1.05rem; margin: 20px 0 8px; text-transform: uppercase; letter-spacing: 0.06em; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    ul { margin: 4px 0 8px; padding-left: 20px; }
    li { margin: 2px 0; }
    p { margin: 4px 0 8px; }
    .meta { color: #6b7280; font-size: 0.85rem; margin-bottom: 16px; }
    .content { margin-top: 8px; }
  </style>
</head>
<body>
  <div class="email-shell">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">Generated by Product Pulse Phase 4</div>
    <div class="content">
${body}
    </div>
  </div>
</body>
</html>`;
}

/**
 * Convert plain-text one-pager to Markdown for easy viewing in the editor.
 * ALL CAPS lines become ## headings; lines starting with "- " or "* " become list items.
 * @param {string} bodyText - Plain text report (same format as HTML input)
 * @param {{ title?: string } } opts
 * @returns {string} Markdown document
 */
export function textToMarkdown(bodyText, { title = 'Product Pulse Weekly' } = {}) {
  const lines = bodyText.split(/\n/).map((l) => l.trim()).filter(Boolean);
  const blocks = [];
  let listItems = [];

  function flushList() {
    if (listItems.length) {
      blocks.push(listItems.map((t) => '- ' + t).join('\n'));
      listItems = [];
    }
  }

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const isAllCaps = trimmed === trimmed.toUpperCase() && trimmed.length > 1 && /[A-Z]/.test(trimmed);
    if (isAllCaps) {
      flushList();
      blocks.push('\n## ' + trimmed + '\n');
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      listItems.push(trimmed.slice(2));
    } else {
      flushList();
      blocks.push(trimmed + '\n');
    }
  }
  flushList();

  return '# ' + title + '\n\n*Generated by Product Pulse Phase 4*\n\n' + blocks.join('\n').trim() + '\n';
}
